### ISSUE TITLE
Remove the MAX_FD limit

### ISSUE THREAD

**Issue by randomstuff** [mquinson/simterpose#6]
Simterpose only handles file descriptors < `MAX_FD` (2048) and it does not event detect that the FD is out of bounds. For this reason, it segfaults when trying to use tools such as valgrind which create file descriptor somewhere in ~65535. We should probably some sort of map (and possibly adding a direct-mapped/2-way-associative cache if it turns out to be too slow) instead of a plain array for storing FD infos.

**Comment by mquinson** [comment]
But how the hell is it possible to have file descriptors that are over MAX_FD?? I'm missing something here.

**Comment by mquinson** [comment]
Ok, I'm just ranting to prove that I am naive wrt systems, but your diagnostic and proposed fix are obviously the way to go.
